# Generated by Django 3.1.4 on 2020-12-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201226_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
